accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

eventos/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from django.views.generic.base import TemplateView

from rest_framework import routers
from webapp import views

router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)
router.register(r'Eventos', views.EventoViewSet)

    # url(r'^login/$', auth_views.login, name='login'),
    # url(r'^logout/$', auth_views.logout, name='logout'),

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'api/', include(router.urls)),
    url(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'webapp/', include('webapp.urls', namespace='webapp')),
]

webapp/urls.py
# from django.urls import path
from django.conf.urls import url
# from django.contrib import admin

# from django.views.generic import TemplateView
# from . import views

from .views import (
    EventoList,
    EventoDetail,
    EventoCreation,
    EventoUpdate,
    EventoDelete
)

app_name = 'webapp'
urlpatterns = [

    url(r'^$', EventoList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', EventoDetail.as_view(), name='detail'),
    url(r'^nuevo$', EventoCreation.as_view(), name='new'),
    url(r'^editar/(?P<pk>\d+)$', EventoUpdate.as_view(), name='edit'),
    url(r'^borrar/(?P<pk>\d+)$', EventoDelete.as_view(), name='delete'),

    # ex: /polls/
    # path('kk/', AboutView.as_view()),
    # path('kk/', TemplateView.as_view(template_name="about.html")),
    # path('kk/', TemplateView.as_view(template_name='index.html')),

    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results')

    # path('', TemplateView.as_view(template_name='index.html')),

    # url(r'^$', views.index, name='index'),
    # path(r'^$', TemplateView.as_view(template_name='index.html')),

    # # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

accounts/models.py
from django.db import models

# Create your models here.

webapp/models.py
from django.db import models

from django.contrib.auth.models import User, Group

# Create your models here.


class Evento(models.Model):

    CONFERENCIA = 'CF'
    SEMINARIO = 'SE'
    CONGRESO = 'CG'
    CURSO = 'CU'
    PRESENCIAL = 'PR'
    VIRTUAL = 'VI'

    CATEGORIA_CHOICES = (
        (CONFERENCIA, 'Conferencia'),
        (SEMINARIO, 'Seminario'),
        (CONGRESO, 'Congreso'),
        (CURSO, 'Curso')
    )

    TIPO_CHOICES = (
        (PRESENCIAL, 'Presencial'),
        (VIRTUAL, 'Virtual')
    )

    nombre = models.CharField(
        max_length=1000, help_text='Nombre del evento', verbose_name='Nombre')
    categoria = models.CharField(
        max_length=20, choices=CATEGORIA_CHOICES, help_text='Categoría del evento', verbose_name='Categoría')
    lugar = models.CharField(
        max_length=1000, help_text='Lugar donde se realizará el evento', verbose_name='Lugar')
    direccion = models.CharField(
        max_length=1000, help_text='Dirección donde se realizará el evento', verbose_name='Dirección')
    fecha_inicio = models.DateTimeField(
        help_text='Fecha y hora de inicio del evento', verbose_name='Fecha de inicio')
    fecha_fin = models.DateTimeField(
        help_text='Fecha y hora de finalización del evento', verbose_name='Fecha de finalización')
    tipo = models.CharField(
        max_length=20, choices=TIPO_CHOICES, help_text='Tipo del evento: Presencial o virtual', verbose_name='Tipo')
    userId = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(
        help_text='Fecha y hora de creación del evento', verbose_name='Fecha de creación', auto_now_add=True)

    class Meta:
        verbose_name = "Evento"
        verbose_name_plural = "Eventos"

    def __str__(self):
        tmpTipo = [item[1]
                   for item in self.CATEGORIA_CHOICES if item[0] == self.categoria][0]
        return self.nombre + ' (' + tmpTipo + ')'

    def __unicode__(self):
        return self.nombre

accounts/views.py
# accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

webapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
# from django.views import generic
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy


# from django.views.generic import TemplateView

# Create your views here.

from rest_framework import viewsets
from django.contrib.auth.models import User, Group
from .models import Evento
from .serializers import UserSerializer, GroupSerializer, EventoSerializer

from django.contrib.auth.mixins import LoginRequiredMixin

##########################
# Vistas para CRUD Evento
##########################
class EventoList(LoginRequiredMixin, ListView):
    # template_name = 'webapp/index.html'
    # context_object_name = 'latest_question_list'
    # if request.user.is_authenticated():
    #     queryset = Evento.objects.all().filter(userId = user)
    # else:
    #     queryset = Evento.objects.all()
    model = Evento

    def get_queryset(self):
        return Evento.objects.filter(userId=self.request.user).order_by('-fecha_creacion')

class EventoDetail(LoginRequiredMixin, DetailView):
    model = Evento

class EventoCreation(LoginRequiredMixin, CreateView):
    model = Evento
    success_url = reverse_lazy('webapp:list')
    fields = ['nombre', 'categoria', 'lugar', 'direccion', 'fecha_inicio', 'fecha_fin', 'tipo']

    def form_valid(self, form):
        form.instance.userId = self.request.user
        return super().form_valid(form)

class EventoUpdate(LoginRequiredMixin, UpdateView):
    model = Evento
    success_url = reverse_lazy('webapp:list')
    fields = ['nombre', 'categoria', 'lugar', 'direccion', 'fecha_inicio', 'fecha_fin', 'tipo']

    def form_valid(self, form):
        # if form.instance.userId != self.request.user:
        #     raise ValidationError(self.request.user+"is not the owner of the event")
            # return False
        return super().form_valid(form)

class EventoDelete(LoginRequiredMixin, DeleteView):
    model = Evento
    success_url = reverse_lazy('webapp:list')
##########################
# FIN - Vistas para CRUD Evento
##########################

##########################
# Vistas para API REST
##########################
class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer

class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

class EventoViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows Eventos to be viewed or edited.
    """
    queryset = Evento.objects.all()  # .order_by('-date_joined')
    serializer_class = EventoSerializer
##########################
# FIN - Vistas para API REST
##########################

# DEMO para otro tipo de vistas

# def index(request):
#     context = {
#         'days': Evento.objects.all(),
#     }
#     return render(request, 'webapp/index.html', context)

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- <link rel="icon" href="https://getbootstrap.com/favicon.ico"> -->
  <title>{% block title %}Eventos{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <!-- Add this to <head> -->
  <!-- <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap/dist/css/bootstrap.min.css" /> -->
  <link type="text/css" rel="stylesheet" href="https://getbootstrap.com/docs/3.3/dist/css/bootstrap.min.css" />
  <link type="text/css" rel="stylesheet" href="https://getbootstrap.com/docs/3.3/assets/css/ie10-viewport-bug-workaround.css"
  />
  <link type="text/css" rel="stylesheet" href="https://getbootstrap.com/docs/3.3/examples/signin/signin.css" />
  <link type="text/css" rel="stylesheet" href="https://getbootstrap.com/docs/3.3/assets/js/ie-emulation-modes-warning.js" />

</head>

<body>
  {% if user.is_authenticated %} Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
  {% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a> |
  <a href="{% url 'signup' %}">signup</a>
  {% endif %}

  <main>
    {% block content %} {% endblock %}
  </main>
  <div class="container text-center">
    <p>...</p>
    <a href="{% url 'home' %}">home</a> |
    <!-- <a href="api/">API</a> | -->
    <a href="{% url 'webapp:list' %}">eventos</a>
  </div>
</body>

</html>

templates/home.html
<!-- templates/home.html -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta http-equiv="refresh" content="0; URL='{% url 'webapp:list' %}'" />
  <title>Home</title>
</head>

<body>

</body>

</html>

templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

webapp/templates/webapp/base.html
<!-- djangotemplates/example/templates/base.html -->

{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <title>
        BigData - {% block title %}{% endblock %}
    </title>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    <!-- Bootstrap core CSS -->
    <!-- Add this to <head> -->
            <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap/dist/css/bootstrap.min.css" />
            <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.css" />
      
            <script src="https://unpkg.com/vue"></script>
            <!-- Add this after vue.js -->
            <script src="//unpkg.com/babel-polyfill@latest/dist/polyfill.min.js"></script>
            <script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>
      
          <!-- Custom styles for this template -->
          <link href="floating-labels.css" rel="stylesheet">
      

    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
		{% block head %}{% endblock %}
</head>

<body>
    <div class="header">
        <a href="/webapp/">
        <img class="logo-mobile" src="https://www.uniandes.edu.co/sites/default/files/logo-mobile.png" title="Logo" alt="Home">
        </a>
    </div>
    <div class="container">
        {% block pagecontent %} {% endblock %}
    </div>
</body>

</html>

webapp/templates/webapp/evento_confirm_delete.html
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el curso "{{ object }}"?
    <input type="submit" value="Submit" />
</form>

webapp/templates/webapp/evento_detail.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h1>{{ evento }}</h1>
<p>nombre: <i>{{ evento.nombre }}</i></p>
<p>categoria: <i>{{ evento.categoria }}</i></p>
<p>lugar: <i>{{ evento.lugar }}</i></p>
<p>direccion: <i>{{ evento.direccion }}</i></p>
<p>fecha_inicio: <i>{{ evento.fecha_inicio }}</i></p>
<p>fecha_fin: <i>{{ evento.fecha_fin }}</i></p>
<p>tipo: <i>{{ evento.tipo }}</i></p>
<p>userId: <i>{{ evento.userId }}</i></p>
<p>fecha_creacion: <i>{{ evento.fecha_creacion }}</i></p>


<p>
    <a href="{% url "webapp:list" %}">Regresar</a>
</p>
{% endblock %}

webapp/templates/webapp/evento_form.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

webapp/templates/webapp/evento_list.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h1>Listado de eventos</h1>

<p>
    <a href="{% url "webapp:new" %}">Agregar evento</a>
</p>

<ul>
    {% for evento in object_list %}
        <li>
            <p>{{ evento }}</p>
            <p>
                <a href="{% url "webapp:detail" evento.id %}">Ver</a> | 
                <a href="{% url "webapp:edit" evento.id %}">Editar</a> | 
                <a href="{% url "webapp:delete" evento.id %}">Borrar</a> 
            </p>
        </li>
    {% endfor %}
</ul>
{% endblock %}

webapp/templates/webapp/index.1.html
{% extends 'webapp/base.html' %} {% block title %}RSS{% endblock %} {% block pagecontent %}

<div>
    <table style="width:40%">
        <tr>
            <td><label>Título:</label></td> <td><input id="titulo" type="text" placeholder="Ingrese el título aquí"></td>
        </tr>
        <tr>
            <td><label>Descripción:</label></td><td><input id="descripcion" type="text" placeholder="Ingrese la descripción aquí"></td>
        </tr>
        <tr>
            <td><label>Categoría:</label></td><td><input id="categoria" type="text" placeholder="Ingrese la categoría aquí"></td>
        </tr>
    </table>
</div>
<div>
    <h2>Títulos sin filtro</h2>
    <div id="sinFiltro">


        <!-- {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
            <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p>No polls are available.</p>
        {% endif %} -->
    </div>
</div>
<div>
    <h2>Títulos sin filtro</h2>
    <div id="sinFiltro"></div>
</div>
<div>
    <h2>Títulos sin filtro</h2>
    <div id="sinFiltro"></div>
</div>
<ul>
    {% if latest_question_list %}
    <ul>
    {% for evento in latest_question_list %}
        <li><a href="/{{ evento.id }}/">{{ evento }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No hay eventos disponibles.</p>
    {% endif %}
</ul>

    <!-- {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %} -->

{% endblock %}

webapp/templates/webapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> Vue-js | Django | Crud App</title>
    <meta name="description" content="A simple crud app made with the vue js and django">
    <meta name="keywords" content="vuejs, django, crudapp, restapi">

    <!-- Bootstrap core CSS -->
    <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap/dist/css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.css" />

    <script src="https://unpkg.com/vue"></script>
    <!-- Add this after vue.js -->
    <script src="//unpkg.com/babel-polyfill@latest/dist/polyfill.min.js"></script>
    <script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <!-- Custom styles for this template -->
    <!-- <link href="floating-labels.css" rel="stylesheet"> -->
</head>

<body>
    <div id="app">
        Hello!!
        <p> [[ title ]] </p>
        <ul>
            <li v-for="day in days">
                <h4> Day [[ day ]]</h4>
            </li>
        </ul>
        <ol>
            {% for day in days %}
            <li>
                <h4> Day {{ day }}</h4>
            </li>
            {% endfor %}

        </ol>
        <ol>
            <li v-for="item in info">
                <h4> Day [[ item.nombre ]] ::: [[ item.lugar ]] </h4>
            </li>
        </ol>
        <!-- <ol>
            <li v-for="day in {{days}}">
                    <h4> Day [[ day ]]</h4>
            </li>
        </ol> -->
    </div>
    <script>
        dd = new Vue({
            delimiters: ['[[', ']]'],
            el: '#app',
            data() {
                return {
                    title: 'Welcome to My Journal',
                    days: [4, 6, 7],
                    info: []
                }
            },
            mounted() {
                axios
                    .get('http://localhost:8000/Eventos/?format=json')
                    .then(response => (
                        console.log("response.data", response.data),
                        this.info = response.data
                    ))
            }
        })
    </script>
</body>

</html>